### ISSUE TITLE
SipHash - library not loaded

### ISSUE THREAD

**Issue by Kaven01** [dankogai/swift-bignum#1]
I am using latest master release of BigNum, via swift package manager. XCode 11.5 (just updated today). Everything works when running app in emulator. But on real device, I get SIGABRT just after the application launches, and following error:

dyld: Library not loaded: @rpath/SipHash.framework/SipHash
  Referenced from: /private/var/containers/Bundle/Application/FF881D6F-2AE9-4CAB-9BE8-6709D7E6428E/Calculator2.app/Frameworks/BigNum.framework/BigNum
  Reason: image not found

As I understand it, SipHash is required by BigInt, which is the required by BigNum. I was googling whole day, and I came to conclusion that current version of BigInt should have it repaired. But I have only version 3.1.0, because that is what BigNum depends on. 

Is it possible to do something with it? If it is possible, can BigNum just allow newer versions of BigInt?

**Comment by dankogai** [comment]
Thank you for reporting this.  I've updated `Package.swift` so it uses version 5 of `BigInt` which no longer depends on `SipHash`.  Would you check if this resolves your problem?

https://github.com/dankogai/swift-bignum/commit/9630bc4e203672d3cfc239d936f27f84c1de66fa

**Comment by Kaven01** [comment]
Wow, that was fast. SipHash disappeared, but i have similar problem:

dyld: Library not loaded: @rpath/FloatingPointMath.framework/FloatingPointMath
  Referenced from: /private/var/containers/Bundle/Application/39D17E9C-0060-40DA-BCCA-FEBA2610ECC1/Calculator2.app/Frameworks/BigNum.framework/BigNum
  Reason: image not found
(lldb) 

I am quite new to swift, so maybe I am doing something wrong. After some googling I found that this problem should be resolved by creating new Framework target from the library and depending on it ... but then your readme doesn't say anything about it. Just now, i have only added latest master version of BigNum via PM, and then used it in projects

**Comment by Kaven01** [comment]
Got it! I manually added FloatingPointMath package to the project, and marked it as Embed in Frameworks, Libraries and embedded content. I couldn't do it before, library was not available there. Then it started working. Don't know why i couldn't mark dependencies of other packages as Embed ... but I can if it is primary dependency of my project. Strange that I don't need to do the same with BigInt. 

So, this resolves the problem for me.
