### ISSUE TITLE
Build issue - Multiplatform Project with Xcode 12 - Release 

### ISSUE THREAD

**Issue by mattRGB** [dankogai/swift-bignum#4]
When using build configuration "Release" for a Multiplatform Xcode 12 project (iOS + MacOS - Apple Silicon + Intel) it appears that Float80 is not supported in the Mac Configuration. See attached Screenshot. Maybe it's related to Apple Silicon...
<img width="881" alt="Screenshot 2020-11-28 at 09 10 42" src="https://user-images.githubusercontent.com/67891393/100497231-31f6af00-315a-11eb-87f0-7d17538a6a20.png">

When building for Debug there is no error message, but Float80 seems to behave wrongly...

**Comment by dankogai** [comment]
Fixed in 91baf9d9f14125634920c3b7cb8d3ff559b00b55 . Thanx!
