### ISSUE TITLE
Rounding error

### ISSUE THREAD

**Issue by Kaven01** [dankogai/swift-bignum#5]
Hello, I found something that seems like a bug in BigNum library to me. I have current version, updated today. 

So I have following code, that simulates an operation I have to do. There are printed results in comments. :

> let toround = BigFloat(2) / BigFloat(100)
> print(toround.description) //0.0199999999999999999996
> 
> let pow = BigFloat(10).power(BigInt(2))
> var res = toround * pow
> print (res.description) //1.999999999999999999959
> 
> res = res.rounded(.toNearestOrAwayFromZero)
> print (res.description) //1.0
>
> res = res / pow
> print (res.description) //0.0099999999999999999998

Problem is the third result, just after .rounded() . 1.999999999999999999959 should have been rounded to 2.0, not 1.0 . Am I doing something wrong, or can you fix the bug, please?

**Comment by mgriebling** [comment]
This is a typical misunderstanding people have with floating point numbers.  **Some numbers just cannot be exactly represented as binary fractions.**  Your example of `0.02` is one such number. Decimal floating point numbers (as used in your hand-held calculator) use Decimal floating point math in which case `0.02` **is exact** and operations on such a number are also exact.

The number `0.02` in binary fractional (IEEE 754 64-bit format) = `00111110010011001100110011001101` which is exactly equal to `0.20000000298023223876953125`.  The next lower binary fraction would be `00111110010011001100110011001100` which is exactly `0.199999988079071044921875`.  So, you see, it will never be possible to represent `0.2` exactly, unless you use decimal floating point numbers which are stored entirely differently.

**Comment by dankogai** [comment]
The explanation above by @mgriebling is 💯.
