### ISSUE TITLE
Power of a negative number

### ISSUE THREAD

**Issue by Kaven01** [dankogai/swift-bignum#6]
Hi, I found a bug in BigFloat.power() (or BigFloat.pow() ) . It crashes when counting power of a negative value, like this:

>             let val = BigFloat(-3)
>             let res = val.power(8) //crash
>             print(res.description)

I believe that it is due to counting log of a negative value in the implementation of power()

**Comment by dankogai** [comment]
Acknowleged.

`man pow` says:
>   pow(x, y) returns a NaN and raises the "invalid" floating-point exception
     for finite x < 0 and finite non-integer y.

In this particular case, it should not use `log` internally,  It should multiply `y` times (and return reciprocal if negative).

**Comment by dankogai** [comment]
Fixed in https://github.com/dankogai/swift-bignum/commit/3694dda8c1f5462cc6cd94902e9396559c906f1a .  It was simply that the negative base case was totally disregarded.  It down not even use `log` because the exponent is `IntType`.

```diff
--- a/Sources/BigNum/GenericMath.swift
+++ b/Sources/BigNum/GenericMath.swift
@@ -141,6 +141,11 @@ extension BigFloatingPoint {
         if self.isNaN || self.isInfinite || self.isZero {
             return Self(Double.pow(self.asDouble, Self(y).asDouble))
         }
+        if self < 0 {
+            let isOdd = y & 1 == 1
+            let magnitude = (-self).power(y, precision:px, debug:debug)
+            return isOdd ? -magnitude : +magnitude
+        }
         if Self.expLimit < Swift.abs(Self.log(self) * Self(y)).asMixed.0 {
             return y < 0 ? 0 : +Self.infinity
         }
```
